### ISSUE TITLE
RegExp allow invalid format

### ISSUE THREAD

**Issue by paulomcnally** [christopher-ramirez/nic-id#1]
**Bad**
http://rubular.com/r/lCHtSkk3jB

**Ok**
http://rubular.com/r/u6Ts0PfhZP

Line: https://github.com/christopher-ramirez/nic-id/blob/master/index.js#L10

**Comment by paulomcnally** [comment]
Alternative: http://rubular.com/r/QpZinvBCkE

Replace space with \s "Any whitespace character"

**Comment by christopher-ramirez** [comment]
:+1:

**Comment by paulomcnally** [comment]
This allow only aA..zZ http://rubular.com/r/zYdYTxZfej

**Comment by christopher-ramirez** [comment]
Suggestions applied on master!
