### ISSUE TITLE
module.exports.NicaraguanId = NicaraguanId

### ISSUE THREAD

**Issue by paulomcnally** [christopher-ramirez/nic-id#2]
**Alternative:**

```
module.exports = NicaraguanId
```

https://github.com/christopher-ramirez/nic-id/blob/master/index.js#L46

**Implementation:**

```
var NicaraguanId = require('../lib'); // or require('nic-id');
var idDoc = new NicaraguanId('000-010180-0001A')
```

**Comment by christopher-ramirez** [comment]
Actually what your are suggesting was the way I exported `NicaraguanId` class on first drafts of the module. But latter, I though this module may include other classes in the future, maybe an tax number, of something like that. For this reason, I changed it to the current implementation.

**Comment by paulomcnally** [comment]
For multiple module https://www.npmjs.com/package/debug :)

Example: https://github.com/strongloop/loopback-connector-mssql/blob/master/lib/mssql.js#L6

**Comment by hosmelq** [comment]
#4 😜

**Comment by christopher-ramirez** [comment]
Thank guys!
